# .github/workflows/deploy-streamlit.yml

name: Deploy to Streamlit Cloud

# Trigger on pushes to the main branch
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Set up Python 3.10
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Reconstruct service account JSON from GitHub Secret
      - name: Write service account JSON
        run: |
          echo "$SERVICE_ACCOUNT_JSON" > summarizely_sa.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      # 5) (Optional) Lint your code for style issues
      - name: Lint with flake8 (optional)
        run: |
          pip install flake8
          flake8 --max-line-length=100 .

      # 6) List files to confirm summarizely_sa.json exists
      - name: Verify files
        run: ls -al

      # 7) Deploy to Streamlit Cloud
      #    You must have already authorized this repo in Streamlit Cloud
      - name: Deploy to Streamlit Cloud
        uses: garygrossgarten/github-action-streamlit@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          app_file_path: streamlit_app.py
