# .github/workflows/deploy.yml

name: Prepare Summarizely for Streamlit Cloud

# Trigger this workflow whenever code is pushed to main
on:
  push:
    branches: [main]

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Set up Python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3) Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Verify files (environment vars handle service account at runtime)
      - name: List repository contents
        run: ls -al .

      # (No “write service account JSON” step needed—app writes from env at runtime)
